### PR TITLE
Update list.handlebars

### PR DESCRIPTION
**Pull request by MingyuYao**
Integrate the search functionality to restaurant listing page.

### CODE REVIEW

**Review by simongao2 — CHANGES_REQUESTED** [review]
Let's try not to put inline JavaScript in our HTML. I would recommend moving the JavaScript to a file in public/js and use our partials function to load the file accordingly. See the views/partials folder for examples of how to do this and in our routing. There may be a handlebars file to handle loading the script already for the list page in views/partials.

Edit: Same for CSS

**Review by simongao2 — CHANGES_REQUESTED** [review]
Can you just add the code in fname.js into restaurantList.js? Just so that we only load 1 JS file on the page.

**Comment by MingyuYao** [comment]
Check out my update on Search Bar.

**Review by simongao2 — APPROVED** [review]
As long as the other components work, lgtm.

**Pull request merged**
